/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import atores.Admin;
import atores.Cliente;
import backend.EstruturaDeDados;
import javax.swing.JOptionPane;
import util.UtilFunctions;

/**
 *
 * @author Jonathan
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAdministrador
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSalvarCad = new javax.swing.JButton();
        labelNomeCad = new javax.swing.JLabel();
        textFieldNomeCad = new javax.swing.JTextField();
        labelCpfCad = new javax.swing.JLabel();
        textFieldCpfCad = new javax.swing.JTextField();
        labelTelefoneCad = new javax.swing.JLabel();
        textFieldTelefoneCad = new javax.swing.JTextField();
        labelEmailCad = new javax.swing.JLabel();
        textFieldEmailCad = new javax.swing.JTextField();
        labelEnderecoCad = new javax.swing.JLabel();
        textFieldEnderecoCad = new javax.swing.JTextField();
        labelLoginCad = new javax.swing.JLabel();
        textFieldLoginCad = new javax.swing.JTextField();
        labelSenhaCad = new javax.swing.JLabel();
        textFieldSenhaCad = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSair = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastro Cliente");
        setResizable(false);

        botaoSalvarCad.setText("Salvar");
        botaoSalvarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarCadActionPerformed(evt);
            }
        });

        labelNomeCad.setText("Nome:");

        textFieldNomeCad.setToolTipText("No mínimo 7 caracteres");

        labelCpfCad.setText("Cpf:");

        textFieldCpfCad.setToolTipText("Apenas números");
        textFieldCpfCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCpfCadActionPerformed(evt);
            }
        });

        labelTelefoneCad.setText("Telefone:");

        textFieldTelefoneCad.setToolTipText("formato: XXXXX-XXXX");

        labelEmailCad.setText("Email:");

        textFieldEmailCad.setToolTipText("formato: jose@arial.com");

        labelEnderecoCad.setText("Endereço:");

        textFieldEnderecoCad.setToolTipText("formato: Rua Madalena, 66, Barroca, BH");

        labelLoginCad.setText("Login:");

        textFieldLoginCad.setToolTipText("No mínimo 5 caracteres e no máximo 15");
        textFieldLoginCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoginCadActionPerformed(evt);
            }
        });

        labelSenhaCad.setText("Senha:");

        textFieldSenhaCad.setToolTipText("No mínimo 5 caracteres e no máximo 15");

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        menuAjuda.setText("Ajuda");
        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNomeCad)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldSenhaCad, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(textFieldLoginCad)
                            .addComponent(textFieldEnderecoCad)
                            .addComponent(textFieldEmailCad)
                            .addComponent(textFieldCpfCad)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoSalvarCad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(labelTelefoneCad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(labelEmailCad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelEnderecoCad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(labelLoginCad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(labelSenhaCad)))
                                .addGap(36, 36, 36))
                            .addComponent(textFieldNomeCad)
                            .addComponent(textFieldTelefoneCad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(labelCpfCad)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelNomeCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(labelCpfCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTelefoneCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTelefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmailCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEnderecoCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLoginCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldLoginCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSenhaCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(botaoSalvarCad)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCpfCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCpfCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCpfCadActionPerformed

    private void textFieldLoginCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoginCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoginCadActionPerformed

    private void botaoSalvarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarCadActionPerformed
        // TODO add your handling code here:
        EstruturaDeDados ed = EstruturaDeDados.getInstance();
        boolean isCadastroOk = false;
        System.out.println("debug " + textFieldLoginCad.getText());
        if (textFieldNomeCad.getText() == null || textFieldNomeCad.getText().length() < 7){
            JOptionPane.showMessageDialog(rootPane, "Erro: Nome inválido, insira novamente.");
        } else if (textFieldCpfCad.getText() == null || UtilFunctions.isValidCPF(textFieldCpfCad.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Erro: Cpf inválido, insira novamente.");
        } else if (textFieldTelefoneCad.getText() == null || textFieldTelefoneCad.getText().length() < 8 /*||UtilFunctions.isTelefone(textFieldTelefoneCad.getText()) == false*/){
            JOptionPane.showMessageDialog(rootPane, "Erro: Telefone inválido, insira novamente.");
        } else if (textFieldEmailCad.getText() == null || UtilFunctions.isValidEmailAddress(textFieldEmailCad.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Erro: Email inválido, insira novamente");
        } else if (textFieldEnderecoCad.getText() == null || textFieldEnderecoCad.getText().length() < 10){
            JOptionPane.showMessageDialog(rootPane, "Erro: Endereço inválido, inisira novamente.");
        } else if (textFieldLoginCad.getText() == null || textFieldLoginCad.getText().length() < 5 || textFieldLoginCad.getText().length() > 15){
            JOptionPane.showMessageDialog(rootPane, "Erro: Login inválido, insira novamente.");
        } else if (textFieldSenhaCad.getText() == null || textFieldSenhaCad.getText().length() < 5 || textFieldSenhaCad.getText().length() > 15){
            JOptionPane.showMessageDialog(rootPane, "Erro: Senha inválida, insira novamente.");
        } else if (ed.checaNomeUsuario(textFieldLoginCad.getText()) == true) {
            JOptionPane.showMessageDialog(rootPane, "Erro: Login já existente, insira novamente.");
        } else {
            System.out.println("Cadastro ok");
            isCadastroOk = true;
        }
        
        if(isCadastroOk){
            String nickname = textFieldLoginCad.getText();
            String telefone = textFieldTelefoneCad.getText();
            String email = textFieldEmailCad.getText();
            String endereco = textFieldEnderecoCad.getText();
            String senha = textFieldSenhaCad.getText();
            String nome = textFieldNomeCad.getText();
            String Cpf = textFieldCpfCad.getText();
            Cliente cliente = new Cliente(nickname, telefone, email, endereco, senha, nome, Cpf);
            System.out.println(cliente);
            ed.cadastrarUsuario(cliente);
        }
    }//GEN-LAST:event_botaoSalvarCadActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:/
        this.setVisible(false);
        this.dispose();
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarCad;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelCpfCad;
    private javax.swing.JLabel labelEmailCad;
    private javax.swing.JLabel labelEnderecoCad;
    private javax.swing.JLabel labelLoginCad;
    private javax.swing.JLabel labelNomeCad;
    private javax.swing.JLabel labelSenhaCad;
    private javax.swing.JLabel labelTelefoneCad;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuSair;
    private javax.swing.JTextField textFieldCpfCad;
    private javax.swing.JTextField textFieldEmailCad;
    private javax.swing.JTextField textFieldEnderecoCad;
    private javax.swing.JTextField textFieldLoginCad;
    private javax.swing.JTextField textFieldNomeCad;
    private javax.swing.JTextField textFieldSenhaCad;
    private javax.swing.JTextField textFieldTelefoneCad;
    // End of variables declaration//GEN-END:variables
}
